// @ts-check
import assert from 'node:assert/strict';
import { describe, test } from 'node:test';

import { coberturaExtractor } from '../../src/extractors/cobertura.js';
import { extract } from '../../src/extractors/index.js';

const FORMAT = 'cobertura';
const UNPARSEABLE = { name: 'ExtractorError', code: 'extractor_report_unparseable' };
const EMPTY = {
  name: 'ExtractorError',
  code: 'extractor_report_empty',
  params: { format: FORMAT },
};
const DOCTYPE = [
  '<!DOCTYPE coverage SYSTEM',
  ' "http://cobertura.sourceforge.net/xml/coverage-04.dtd">',
].join('');

/**
 * Relatório do coverage.py (`coverage xml`): declaração XML, DOCTYPE e comentários dentro da
 * raiz. As classes têm taxas diferentes das da raiz.
 */
const COVERAGE_PY = [
  '<?xml version="1.0" ?>',
  DOCTYPE,
  [
    '<coverage version="7.4.4" timestamp="1714645293312" lines-valid="120" lines-covered="96"',
    ' line-rate="0.8" branches-covered="30" branches-valid="40" branch-rate="0.75"',
    ' complexity="0">',
  ].join(''),
  '\t<!-- Generated by coverage.py: https://coverage.readthedocs.io/en/7.4.4 -->',
  [
    '\t<!-- Based on https://raw.githubusercontent.com/cobertura/web/master/htdocs/xml/',
    'coverage-04.dtd -->',
  ].join(''),
  '\t<sources>',
  '\t\t<source>/home/runner/work/app/app/src</source>',
  '\t</sources>',
  '\t<packages>',
  '\t\t<package name="." line-rate="0.8" branch-rate="0.75" complexity="0">',
  '\t\t\t<classes>',
  [
    '\t\t\t\t<class name="util.py" filename="util.py" complexity="0" line-rate="0.5"',
    ' branch-rate="0.25">',
  ].join(''),
  '\t\t\t\t\t<methods/>',
  '\t\t\t\t\t<lines>',
  '\t\t\t\t\t\t<line number="1" hits="1"/>',
  '\t\t\t\t\t\t<line number="2" hits="0"/>',
  '\t\t\t\t\t</lines>',
  '\t\t\t\t</class>',
  '\t\t\t</classes>',
  '\t\t</package>',
  '\t</packages>',
  '</coverage>',
  '',
].join('\n');

/** Relatório do reporter `cobertura` do Istanbul, com um comentário antes da raiz. */
const ISTANBUL = [
  '<?xml version="1.0" ?>',
  DOCTYPE,
  '<!-- relatório de cobertura dos testes unitários -->',
  [
    '<coverage lines-valid="40" lines-covered="30" line-rate="0.75" branches-valid="10"',
    ' branches-covered="5" branch-rate="0.5" timestamp="1714645293312" complexity="0"',
    ' version="0.1">',
  ].join(''),
  '  <sources>',
  '    <source>/home/runner/work/app/app</source>',
  '  </sources>',
  '  <packages/>',
  '</coverage>',
].join('\n');

/** Relatório do coverage.py sem medição de ramos (`branch = false`). */
const NO_BRANCHES = COVERAGE_PY
  .replace('branches-covered="30" branches-valid="40"', 'branches-covered="0" branches-valid="0"')
  .replace(' branch-rate="0.75"', ' branch-rate="0"');

/**
 * Documento Cobertura mínimo com os atributos indicados no elemento raiz.
 * @param {string} attributes
 * @returns {string}
 */
function withRoot(attributes) {
  return `<?xml version="1.0" ?>\n${DOCTYPE}\n<coverage ${attributes}>\n</coverage>\n`;
}

/**
 * @param {string} text
 * @param {string} [field]
 * @returns {number}
 */
function run(text, field) {
  return extract({ format: FORMAT, path: 'coverage.xml', field }, text);
}

describe('cobertura', () => {
  test('declara os campos do contrato com lines por omissão', () => {
    assert.deepEqual([coberturaExtractor.fields, coberturaExtractor.defaultField], [
      ['lines', 'branches'],
      'lines',
    ]);
  });

  test('usa lines como campo por omissão', () => {
    assert.equal(run(COVERAGE_PY), 80);
  });

  test('lines lê line-rate da raiz x 100', () => {
    assert.equal(run(COVERAGE_PY, 'lines'), 80);
  });

  test('branches lê branch-rate da raiz x 100', () => {
    assert.equal(run(COVERAGE_PY, 'branches'), 75);
  });

  test('ignora declaração XML, DOCTYPE e comentários antes da raiz', () => {
    assert.equal(run(ISTANBUL), 75);
  });

  test('não acumula erro de vírgula flutuante ao converter a taxa (0.57 dá 57)', () => {
    assert.equal(run(withRoot('line-rate="0.57" branch-rate="0.1"')), 57);
  });

  test('aceita taxas com expoente', () => {
    assert.equal(run(withRoot('line-rate="5.7E-1" branch-rate="0"')), 57);
  });

  test('aceita a marca de ordem de bytes e fins de linha CRLF', () => {
    assert.equal(run(`\uFEFF${COVERAGE_PY.replaceAll('\n', '\r\n')}`, 'branches'), 75);
  });

  test('aceita atributos entre plicas', () => {
    assert.equal(run(withRoot("line-rate='0.5' branch-rate='0.25'"), 'branches'), 25);
  });

  test('lines-valid="0" dá extractor_report_empty', () => {
    assert.throws(() => run(withRoot('lines-valid="0" line-rate="1" branch-rate="1"')), EMPTY);
  });

  test('branches-valid="0" dá extractor_report_empty', () => {
    assert.throws(() => run(NO_BRANCHES, 'branches'), EMPTY);
  });

  test('raiz que não é <coverage> dá extractor_report_unparseable', () => {
    const jacoco = [
      '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
      '<!DOCTYPE report PUBLIC "-//JACOCO//DTD Report 1.1//EN" "report.dtd">',
      '<report name="app"><counter type="LINE" missed="2" covered="8"/></report>',
    ].join('');
    assert.throws(() => run(jacoco), {
      ...UNPARSEABLE,
      params: { format: FORMAT, reason: 'root element is <report>, expected <coverage>' },
    });
  });

  test('atributo em falta dá extractor_report_unparseable', () => {
    assert.throws(() => run(withRoot('line-rate="0.9"'), 'branches'), {
      ...UNPARSEABLE,
      params: { format: FORMAT, reason: 'missing attribute "branch-rate" on <coverage>' },
    });
  });

  test('taxa não numérica dá extractor_report_unparseable', () => {
    assert.throws(() => run(withRoot('lines-valid="10" line-rate="NaN"')), UNPARSEABLE);
  });

  test('taxa não finita dá extractor_report_unparseable', () => {
    assert.throws(() => run(withRoot('line-rate="1e999"')), UNPARSEABLE);
  });

  test('taxa maior do que 1 dá extractor_report_unparseable', () => {
    assert.throws(() => run(withRoot('line-rate="80"')), {
      ...UNPARSEABLE,
      params: { format: FORMAT, reason: 'attribute "line-rate" is not between 0 and 1: "80"' },
    });
  });

  test('taxa negativa dá extractor_report_unparseable', () => {
    assert.throws(() => run(withRoot('line-rate="-0.5"')), UNPARSEABLE);
  });

  test('ficheiro vazio dá extractor_report_empty', () => {
    assert.throws(() => run('\n'), EMPTY);
  });

  test('texto sem elementos XML dá extractor_report_unparseable', () => {
    assert.throws(() => run('line-rate=0.8'), UNPARSEABLE);
  });

  test('campo desconhecido dá extractor_field_unknown', () => {
    assert.throws(() => run(COVERAGE_PY, 'functions'), {
      name: 'ExtractorError',
      code: 'extractor_field_unknown',
      params: { format: FORMAT, field: 'functions', known: 'lines, branches' },
    });
  });
});
